language: haxe

sudo: required

matrix:
  include:
    - haxe: development
      os: linux
      dist: trusty
    - haxe: development
      os: osx
      osx_image: xcode8
    - haxe: development
      os: osx
      osx_image: xcode7.1

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get update -y;
    sudo apt-get install gcc-multilib -y;
    fi
  - make ARCH=32 all
  - sudo make install_lib
  
script:
  - haxe -hl hello.hl -cp other/tests -main HelloWorld -D interp
  - ./hl hello.hl
  - haxe -hl src/_main.c -cp other/tests -main HelloWorld && make hlc
